server:
  port: 8087
  address: 0.0.0.0

spring:
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.211.0.210:3307/nova_chat?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: 'mysql_pYDshf'
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 60000
      connection-timeout: 10000
      pool-name: NovaChatHikari

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      update-strategy: not_null
  mapper-locations: classpath*:/mapper/**/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.wang.novachat: info
    com.wang.novachat.chat.mapper: debug
    org.springframework.jdbc.core: warn
    com.zaxxer.hikari: warn
    org.apache.ibatis: warn

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
  packages-to-scan: com.wang.novachat.chat.controller
#  overridden:
#    server: http://129.211.0.210:8080
#    context-path: /api/chat
