server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: nova-user
          uri: lb://nova-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: info
    reactor.netty.http.client: info
